# 服务配置参数
server:
  name: "go-chat"
  port: 5757
# PostgreSQL配置
postgres:
  host: "127.0.0.1"
  port: 5432
  name: "postgres"
  password: "postgres"
  database: "go-chat"
# Redis配置
redis:
  addr: "127.0.0.1:6379"
  db: 0
  password: "123456"